FROM atomicorp/ossec-docker

# copy config
#COPY ossec.conf /var/ossec/etc/ossec.conf

# restart ossec
#RUN ["/var/ossec/bin/syscheck_update", "-a"]
#RUN ["/var/ossec/bin/syscheck_update", "-l"]
#RUN ["/var/ossec/bin/ossec-control", "restart"]