[entryPoints]
  [entryPoints.web]
    address = ":80"
  [entryPoints.websecure]
    address = ":443"
  [entryPoints.webmin]
    address = ":10000"
  [entryPoints.dns]
    address = ":53"

[accessLog]

[api]
  dashboard = true
  insecure = true

[providers.docker]
  watch = true
  exposedByDefault = false